version: "3.8"

services:

  django:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    container_name: postgres_db
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    restart: always

  celery-worker:
    restart: always
    build:
      context: .
    env_file:
      - ./.env
    depends_on:
      - django
      - redis
    command: "celery -A backend worker -l info"

  celery-beat:
    restart: always
    build:
      context: .
    env_file:
      - ./.env
    depends_on:
      - django
      - redis
    command: "celery -A backend beat -l info"

  flower:
    image: mher/flower
    ports:
      - "5556:5555"
    env_file:
      - ./.env
    depends_on:
      - redis
      - django
      - celery-worker
      - celery-beat