# Generated by Django 4.2.3 on 2023-07-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subscribed_mail',
        ),
    ]
