# Generated by Django 4.2.3 on 2023-07-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0002_remove_contact_subscribed_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subscribed_mail',
            field=models.BooleanField(default=False, help_text='I want to receive mails.', max_length=50),
        ),
    ]
