# Generated by Django 4.2.3 on 2023-07-27 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_email', '0005_remove_contact_id_alter_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='user_contact', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
